# Generated by Django 5.2.11 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_general_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_general",
            field=models.BooleanField(
                default=False,
                help_text="If set, this dept cannot be combined with others on a post.",
            ),
        ),
    ]
