# Generated by Django 5.2.11 on 2026-03-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_deptmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("portuguese_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#64748b", max_length=20)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_teams",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-team",
                "verbose_name_plural": "Sub-teams",
                "ordering": ["name"],
            },
        ),
    ]
