# Generated by Django 5.2.11 on 2026-02-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostDept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("elec", "Electronics"),
                            ("dev", "Software Engineering"),
                            ("math", "Statistics"),
                            ("finance", "Finance"),
                            ("relations", "External Relations"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dept_entries",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "dept")},
            },
        ),
    ]
