# Generated by Django 5.2.11 on 2026-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postdept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdept",
            name="dept",
            field=models.CharField(
                choices=[
                    ("elec", "Electronics"),
                    ("dev", "Software + Firmware"),
                    ("math", "Geography and Statistics"),
                    ("finance", "Finance"),
                    ("relations", "External Relations"),
                ],
                max_length=20,
            ),
        ),
    ]
