# Generated by Django 5.2.11 on 2026-03-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_postdept_dept"),
        ("core", "0002_populate_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="postdept",
            name="dept_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_entries",
                to="core.department",
            ),
        ),
        migrations.AlterField(
            model_name="postdept",
            name="dept",
            field=models.CharField(max_length=20),
        ),
    ]
