# Generated by Django 5.2.11 on 2026-02-28 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dept_other",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dept_main",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elec", "Electronics"),
                    ("dev", "Software Engineering"),
                    ("math", "Statistics"),
                    ("finance", "Finance"),
                    ("relations", "External Relations"),
                ],
                max_length=20,
                verbose_name="Main Department",
            ),
        ),
        migrations.CreateModel(
            name="UserDeptOther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("elec", "Electronics"),
                            ("dev", "Software Engineering"),
                            ("math", "Statistics"),
                            ("finance", "Finance"),
                            ("relations", "External Relations"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dept_other_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dept")},
            },
        ),
    ]
