# Generated by Django 5.2.11 on 2026-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_user_dept_other_remove_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dept_main",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elec", "Electronics"),
                    ("dev", "Software + Firmware"),
                    ("math", "Geography and Statistics"),
                    ("finance", "Finance"),
                    ("relations", "External Relations"),
                ],
                max_length=20,
                verbose_name="Main Department",
            ),
        ),
        migrations.AlterField(
            model_name="userdeptother",
            name="dept",
            field=models.CharField(
                choices=[
                    ("elec", "Electronics"),
                    ("dev", "Software + Firmware"),
                    ("math", "Geography and Statistics"),
                    ("finance", "Finance"),
                    ("relations", "External Relations"),
                ],
                max_length=20,
            ),
        ),
    ]
