# Generated by Django 5.2.11 on 2026-03-01 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_populate_departments"),
        ("home", "0003_alter_user_dept_main_alter_userdeptother_dept"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dept_main_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaders",
                to="core.department",
                verbose_name="Main Department (FK)",
            ),
        ),
        migrations.AddField(
            model_name="userdeptother",
            name="dept_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="core.department",
            ),
        ),
    ]
