# Generated by Django 5.2.11 on 2026-03-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_populate_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="curriculum",
            field=models.FileField(blank=True, null=True, upload_to="curricula/"),
        ),
    ]
