# Generated by Django 5.2.11 on 2026-03-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_add_curriculum_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dept_main",
        ),
        migrations.DeleteModel(
            name="UserDeptOther",
        ),
    ]
